name: l2acenv
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - numpy=1.20.2
  - pandas
  - matplotlib
  - pillow
  - pip
  - plotly
  - scikit-learn=0.24.2
  - seaborn
  - tqdm
#  - python=3.7.3
  - pytorch=1.1.0
  - torchvision=0.2.2
  - pyyaml
  - tqdm=4.59.0 
#  - cudatoolkit=11.1
  
