name: l2acenv
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - numpy=1.20.2
  - pandas
  - matplotlib
  - pillow
  - pip
  - plotly
  - scikit-learn
  - seaborn
#  - python=3.7.3
  - pytorch=1.1.0
  - torchvision=0.2.2
  - pyyaml
#  - cudatoolkit=11.1
  
