dataset_path: '../datasets/CATS_DOGS'
dataset_class: CatDogDataset
model_path: '../networks/CATDOG/test_model.pt'
model_class: CATDOGNetwork
criterion: CrossEntropyLoss
optimizer: Adam
learning_rate: 0.001
batch_size: 10
epochs: 5
