dataset_path: '../datasets/CATS_DOGS'
dataset_class: CatDogDataset
model_path: '../networks/CATDOG/test_model.pt'
training_history_path: '../networks/CATDOG/test_model_history'
figures_path: '../figures/CATDOG_'
model_class: CATDOGNetwork
criterion: CrossEntropyLoss
optimizer: Adam
learning_rate: 0.001
batch_size: 10
epochs: 5
