dataset_path: 'datasets/CIFAR100'
dataset_class: CIFAR100Dataset
model_path: 'networks/CIFAR100/encoder/resnet50_features.pt'
model_class: ResNet50Features
training_history_path: 'networks/CIFAR100/encoder/resnet50_features_model_history'
criterion: CrossEntropyLoss
optimizer: Adam
learning_rate: 0.001
batch_size: 10
epochs: 5
figures_path: '/figures/CIFAR100_'
