## Experiment
name: 'e0000'

## Paths and classes
dataset_path: 'datasets/CIFAR100'
dataset_class: CIFAR100Dataset
image_resize: 64
model_path: 'networks/CIFAR100/encoder/resnet50.pt'
model_class: ResNet50Features
feature_layer: avgpool
training_history_path: 'networks/CIFAR100/encoder/resnet50_setup_train_history'
figures_path: 'figures/CIFAR100_'

## L2AC parameters
top_n: 1
train_classes: 3
test_classes: 3
train_samples_per_cls: 5
randomize_samples: True


## Training/loading parameters
load_memory: False
enable_training: True
save_images: True