## Experiment
name: 'e0000'

## Paths and classes
dataset_path: CIFAR100
dataset_class: CIFAR100Dataset
image_resize: 224
model_class: ResNet50
feature_layer: avgpool
feature_scaling: max_value #sigmoid max_value
unfreeze_layer: 62     #62 62 10 30
pretrained: True
remove_teapot: True


## L2AC parameters
top_n: 1

class_ratio: 
  encoder_trn: 50
  meta_trn: 20
  meta_val: 20
  meta_tst: 20


sample_ratio:
  encoder_train_samples: 500
  l2ac_train_samples: 350
  l2ac_val_samples: 100
  l2ac_test_samples: 100






train_samples_per_cls: 500
randomize_samples: True

