## Experiment
name: 'e_t_0012'

## Paths and classes
dataset_path: TinyImageNet #'datasets/TinyImageNet' #'datasets/CIFAR100'
dataset_class: TinyImageNetDataset #TinyImageNetDataset #CIFAR100Dataset
image_resize: 224
model_class: AlexNet
feature_layer: features
feature_scaling: max_value #sigmoid max_value
unfreeze_layer: 10
pretrained: True

## Training hyperparameters
criterion: CrossEntropyLoss
optimizer: SGD
learning_rate: 0.001
batch_size: 100
epochs: 50
  
## L2AC parameters
class_ratio: 
  encoder_train: 100
  l2ac_train: 20
  l2ac_test: 20


