## Experiment
name: 'e_c_0004'

## Paths and classes
dataset_path: TinyImageNet #'datasets/TinyImageNet' #'datasets/CIFAR100'
dataset_class: TinyImageNetDataset #TinyImageNetDataset #CIFAR100Dataset
image_resize: 224
model_class: EfficientNet
feature_layer: _avg_pooling
feature_scaling: max_value #sigmoid max_value
unfreeze_layer: 30
pretrained: True

## Training hyperparameters
criterion: CrossEntropyLoss
optimizer: Adam
learning_rate: 0.0001
batch_size: 256
epochs: 2
  
## L2AC parameters
class_ratio: 
  encoder_train: 50
  l2ac_train: 20
  l2ac_val: 20
  l2ac_test: 20
  
sample_ratio:
  encoder_train_samples: 500
  l2ac_train_samples: 350
  l2ac_val_samples: 100
  l2ac_test_samples: 100