## Experiment
name: 'e0001'

## Paths and classes
dataset_path: 'datasets/CIFAR100'
dataset_class: CIFAR100Dataset
image_resize: 64
model_class: EfficientNet
feature_layer: _avg_pooling
model_path: networks
pretrained: True

## Training hyperparameters
criterion: CrossEntropyLoss
optimizer: SGD
learning_rate: 0.001
batch_size: 100
epochs: 2
  
## L2AC parameters
train_classes: 100
test_classes: 20

## Training/loading parameters
load_memory: False
enable_training: True
save_images: True
