## Experiment
name: 'e_c_0004'

## Paths and classes
dataset_path: CIFAR100 #'datasets/TinyImageNet' #'datasets/CIFAR100'
dataset_class: CIFAR100Dataset #TinyImageNetDataset #CIFAR100Dataset
image_resize: 224
model_class: EfficientNet
feature_layer: _avg_pooling
feature_scaling: max_value #sigmoid max_value
unfreeze_layer: 0
pretrained: True

## Training hyperparameters
criterion: CrossEntropyLoss
optimizer: SGD
learning_rate: 0.0001
batch_size: 100
epochs: 50
  
## L2AC parameters
class_ratio: 
  encoder_trn: 0
  meta_trn: 50
  meta_val: 5
  meta_tst: 20

sample_ratio:
  encoder_train_samples: 500
  l2ac_train_samples: 350
  l2ac_val_samples: 100
  l2ac_test_samples: 100