## Experiment
name: 'e_c_0004'

## Paths and classes
dataset_path: CIFAR100 #'datasets/TinyImageNet' #'datasets/CIFAR100'
dataset_class: CIFAR100Dataset #TinyImageNetDataset #CIFAR100Dataset
image_resize: 224
model_class: ResNet50
feature_layer: avgpool
unfreeze_layer: 62
model_path: networks
pretrained: True

## Training hyperparameters
criterion: CrossEntropyLoss
optimizer: SGD
learning_rate: 0.001
batch_size: 100
epochs: 2
  
## L2AC parameters
train_classes: 100
test_classes: 20

## Training/loading parameters
load_memory: False
enable_training: True
save_images: True
