## Experiment
name: 'e0001'

## Paths and classes
dataset_path: 'datasets'
dataset_class: CIFAR100Dataset
model_class: resnet50
pretrained: False

## Training hyperparameters
criterion: CrossEntropyLoss
optimizer: Adam
learning_rate: 0.01
batch_size: 400
epochs: 30
  
## L2AC parameters
train_classes: 100
test_classes: 20

## Training/loading parameters
load_memory: False
enable_training: True
save_images: True
