## Experiment
name: 
  ['0004', '0004', '0004', '0004']

variable: top_n

figure_path: 'figures/L2AC_'


# ## Paths and classes
# dataset_path: 'datasets/CIFAR100'
# dataset_class: MetaDataset
# model_path: 'networks/CIFAR100/L2AC.pt'
# model_class: L2AC
# training_history_path: 'networks/CIFAR100/encoder/L2AC_model_history'

# ## Training hyperparameters
# criterion: BCEWithLogitsLoss
# optimizer: Adam
# learning_rate: 0.0001
# epochs: 20

# ## L2AC parameters
# top_k: 5
# top_n: 9
# train_classes: 20
# test_classes: 20
# train_samples_per_cls: 500
# probability_threshold: 0.5

# ## Dataset preparation parameters
# same_class_reverse: False
# same_class_extend_entries: False



# ## Training/loading parameters
# load_memory: False
# enable_training: False
# save_images: True
