## Experiment
name: '0001_effnet'

## Paths and classes
dataset_path: TinyImageNet
dataset_class: MetaDataset
model_path: 'networks/CIFAR100/L2AC.pt'
model_class: L2AC
encoder: EfficientNet
feature_layer: _avg_pooling
image_resize: 224
unfreeze_layer: 118    #62 62 6 8
training_history_path: 'networks/CIFAR100/encoder/L2AC_model_history'
figures_path: 'figures/CIFAR100_'

## Training hyperparameters
criterion: BCEWithLogitsLoss
optimizer: SGD
learning_rate: 0.0001
batch_size: 256
epochs: 50

## L2AC parameters
top_k: 5
top_n: 4

class_ratio: 
  encoder: 100
  l2ac_train: 20
  l2ac_test: 20

train_samples_per_cls: 500
probability_threshold: 0.5

## Dataset preparation parameters
same_class_reverse: False
same_class_extend_entries: False



## Training/loading parameters
load_memory: False
enable_training: True
save_images: True
create_similarity_gif: True
