## Experiment
name: 'l2ac_batch_no_pos_weigth'

## Paths and classes
dataset_path: 'datasets/CIFAR100'
dataset_class: MetaDataset
model_path: 'networks/CIFAR100/L2AC.pt'
model_class: L2AC
training_history_path: 'networks/CIFAR100/encoder/L2AC_model_history'
figures_path: 'figures/CIFAR100_'

## Training hyperparameters
criterion: BCEWithLogitsLoss
# criterion: BCELoss

optimizer: Adam
learning_rate: 0.0001
batch_size: 256  
epochs: 50
max_trn_batch: 1562


## L2AC parameters
top_k: 5
top_n: 10
train_classes: 80
train_samples_per_cls: 500
probability_threshold: 0.5


## Training/loading parameters
load_memory: False
enable_training: True
save_images: True
