## Experiment
name: ['l_t_m_0001'] #, 'l_t_m_0002', 'l_t_m_0003', 'l_t_m_0004','l_t_m_0005', 'l_t_m_0006', 'l_t_m_0007']



figure_labels: ['L2AC-default'] #, 'L2AC-cosine', 'L2AC-no-lstm', 'L2AC-extended-similarity', 'L2AC-smaller-fc', 'L2AC-abssub', 'L2AC_concat']

figure_title: 'models'

experiment_name: 'l2ac_encoders'

variable: model_class
unknown_classes: [0, 5, 10]
tst_memory_cls: 80
figure_path: 'results/'



