## Experiment
name: 'l_a_0001'

## Paths and classes
dataset_path: amazon
dataset_class: MetaDataset
model_class: L2AC
encoder: AmazonEncoder
feature_layer: layer
image_resize: 224
unfreeze_layer: 62    #62 62 6 8

## Training hyperparameters
criterion: bce_loss_default
optimizer: Adam
learning_rate: 0.0001
batch_size: 256
epochs: 50


## L2AC parameters
top_k: 5
top_n: 9
class_ratio: 
  encoder_train: 100
  l2ac_train: 900
  l2ac_test: 100

test_class_selection: diff_cls
feature_scaling: normal #sigmoid max_value
two_step_training: True
train_matching_layer_only: False

train_samples_per_cls: 100
probability_threshold: 0.5

## Dataset preparation parameters
same_class_reverse: False
same_class_extend_entries: False

## Training/loading parameters
create_similarity_gif: True
