## Experiment
name: '0001'

## Paths and classes
dataset_path: CIFAR100
dataset_class: MetaDataset
model_class: L2AC
encoder: ResNet50
feature_layer: avgpool
image_resize: 224
unfreeze_layer: 62    #62 62 6 8

## Training hyperparameters
criterion: BCEWithLogitsLoss
optimizer: Adam
learning_rate: 0.0001
batch_size: 256
epochs: 50

## L2AC parameters
top_k: 5
top_n: 4

class_ratio: 
  encoder_train: 50
  l2ac_train: 20
  l2ac_test: 20

test_class_selection: same_cls

train_samples_per_cls: 500
probability_threshold: 0.5

## Dataset preparation parameters
same_class_reverse: False
same_class_extend_entries: False

## Training/loading parameters
create_similarity_gif: True
