## Experiment
name: ['l_t_e_0003']

figure_labels: ['Alexnet']
figure_title: 'Encoders'

experiment_name: 'l2ac_encoders'

variable: model_class
unknown_classes: [0, 5, 10]
tst_memory_cls: 10
figure_path: 'results/'



