## Experiment
name: '0004'

## Paths and classes
dataset_path: TinyImageNet
dataset_class: MetaDataset
model_class: L2AC
encoder: ResNet50
feature_layer: avgpool
image_resize: 224
unfreeze_layer: 0    #62 62 6 8

## Training hyperparameters
criterion: bce_loss_default
optimizer: Adam
learning_rate: 0.0001
batch_size: 256
epochs: 2

## L2AC parameters
top_k: 5
top_n: 9

class_ratio: 
  encoder_trn: 0
  meta_trn: 80
  meta_val: 20
  meta_tst: 80

sample_ratio:
  encoder_train_samples: 500
  l2ac_train_samples: 350
  l2ac_val_samples: 100
  l2ac_test_samples: 100

test_class_selection: same_cls
feature_scaling: max_value #sigmoid max_value
two_step_training: False
freeze_matching_layer: False



train_samples_per_cls: 500
probability_threshold: 0.5

## Dataset preparation parameters
same_class_reverse: False
same_class_extend_entries: False

## Training/loading parameters
create_similarity_gif: True
