## Experiment
name: '0000'

## Paths and classes
dataset_path: 'datasets/CIFAR100'
dataset_class: MetaDataset
model_path: 'networks/CIFAR100/L2AC.pt'
model_class: L2AC
training_history_path: 'networks/CIFAR100/encoder/L2AC_model_history'
figures_path: 'figures/CIFAR100_'

## Training hyperparameters
criterion: BCEWithLogitsLoss
optimizer: Adam
learning_rate: 0.0001
batch_size: 256  
epochs: 200

## L2AC parameters
top_k: 5
top_n: 10
train_classes: 20
test_classes: 20
train_samples_per_cls: 500
probability_threshold: 0.5

## Dataset preparation parameters
same_class_reverse: True
same_class_extend_entries: False



## Training/loading parameters
load_memory: False
enable_training: True
save_images: True
