## Paths and classes
dataset_path: 'datasets/FashionMNIST'
dataset_class: FashionMNISTDataset
model_path: 'networks/Fashion_MNIST/encoder/resnet50_features.pt'
model_class: ResNet50Features
training_history_path: 'networks/MNISTFashion/encoder/resnet50_setup_train_history'
figures_path: 'figures/FashionMNIST_'

## Training hyperparameters
criterion: BCELoss
optimizer: Adam
learning_rate: 0.001
batch_size: 10
epochs: 10

## L2AC parameters
top_k: 20
top_n: 10
train_classes: 5
train_samples_per_cls: 500

## Training/loading parameters
load_memory: False
enable_training: True
save_images: True