dataset_path: '../datasets/FashionMNIST'
dataset_class: FashionMNISTDataset
model_path: '../networks/Fashion_MNIST/test_model.pt'
model_class: FashionMNISTNetwork
criterion: CrossEntropyLoss
optimizer: Adam
learning_rate: 0.001
batch_size: 10
epochs: 5
