## Experiment
object_name: 'object_1'

experiment_name: 'l_t_teapot_no_lstm_same'
extend_memory: True
test_new_cls_only: False
memory_dataset: 'webots_dataset_224_close'
input_dataset: 'teapot_photos'

