## Experiment
object_name: 'object_1'

experiment_name: 'l_t_e_0010'
extend_memory: True

## Paths and classes
dataset_path: TinyImageNet
dataset_class: MetaDataset
model_experiment_nr: 0001
encoder: ResNet50
feature_layer: avgpool
image_resize: 224
unfreeze_layer: 62   #62 62 6 8



## Training hyperparameters
criterion: bce_loss_custom
optimizer: Adam
learning_rate: 0.0001
batch_size: 256
epochs: 50

## L2AC parameters
top_k: 5
top_n: 4

class_ratio:
  encoder_train: 100
  l2ac_train: 20
  l2ac_val: 20
  l2ac_test: 20

sample_ratio:
  encoder_train: 500
  l2ac_train: 350
  l2ac_val: 100
  l2ac_test: 100

test_class_selection: same_cls
feature_scaling: max_value #sigmoid max_value
two_step_training: False
freeze_matching_layer: False

train_samples_per_cls: 500
probability_threshold: 0.5

## Dataset preparation parameters
same_class_reverse: False
same_class_extend_entries: False

## Training/loading parameters
create_similarity_gif: True
