## Experiment
name: 'e0000'

## Paths and classes
dataset_path: TinyImageNet
dataset_class: TinyImageNetDataset
image_resize: 224
model_class: ResNet50
feature_layer: avgpool
unfreeze_layer: 62    #62 62 6 8
pretrained: True

## L2AC parameters
top_n: 1
class_ratio: 
  encoder_train: 100
  l2ac_train: 20
  l2ac_test: 20

feature_scaling: normal #sigmoid max_value


train_samples_per_cls: 500
randomize_samples: True



