## Experiment
name: 'e0000'

## Paths and classes
dataset_path: TinyImageNet
dataset_class: TinyImageNetDataset
image_resize: 224
model_class: ResNet50
feature_layer: avgpool
unfreeze_layer: 62    #62 62 6 8
pretrained: True

## L2AC parameters
top_n: 4
class_ratio: 
  encoder_trn: 50
  meta_trn: 20
  meta_val: 20
  meta_tst: 20

sample_ratio:
  encoder_train_samples: 500
  l2ac_train_samples: 350
  l2ac_val_samples: 100
  l2ac_test_samples: 100


feature_scaling: max_value #sigmoid max_value


train_samples_per_cls: 500
randomize_samples: False



