## Experiment
name: 'e0000'

## Paths and classes
dataset_path: 'datasets/TinyImageNet'
dataset_class: TinyImageNetDataset
image_resize: 224
model_path: 'networks/CIFAR100/encoder/resnet50.pt'
model_class: Resnet50
feature_layer: avgpool
pretrained: True
training_history_path: 'networks/CIFAR100/encoder/resnet50_setup_train_history'
figures_path: 'figures/CIFAR100_'

## L2AC parameters
top_n: '4'
train_classes: 21
test_classes: 20
train_samples_per_cls: 500
randomize_samples: True


## Training/loading parameters
load_memory: False
enable_training: True
save_images: True
